-- Create dbt database for dev user
DROP DATABASE fx;
CREATE database fx;
CREATE USER dev WITH PASSWORD 'dbtdev' SUPERUSER;
GRANT ALL PRIVILEGES ON DATABASE fx TO postgres;
GRANT ALL PRIVILEGES ON DATABASE fx TO dev;
\c fx dev;
CREATE SCHEMA fx_hist;
GRANT ALL PRIVILEGES ON SCHEMA fx_hist TO postgres;
GRANT ALL PRIVILEGES ON SCHEMA fx_hist TO dev;
CREATE SCHEMA fx;
GRANT ALL PRIVILEGES ON SCHEMA fx TO postgres;
GRANT ALL PRIVILEGES ON SCHEMA fx TO dev;