
#date,usd,eur,jpy,gbp,chf,nzd,cad,hkd,sgd,myr,twd,krw,idr,cny,sdr
seeds:
  - name: s1_aud1980
    description: "AUD rate for 1980"
    +columns:
      - name: usd
        data_type: double
      - name: eur
        data_type: double
      - name: jpy
        data_type: double
      - name: gbp
        data_type: double
      - name: chf
        data_type: double
      - name: nzd
        data_type: double
      - name: cad
        data_type: double
      - name: hkd
        data_type: double
      - name: sgd
        data_type: double
      - name: myr
        data_type: double
      - name: twd
        data_type: double
      - name: krw
        data_type: double
      - name: idr
        data_type: double
      - name: cny
        data_type: double
      - name: sdr
        data_type: double
  - name: s1_aud1990
    description: "AUD rate for 1990"
    +columns:
      - name: usd
        data_type: double
      - name: eur
        data_type: double
      - name: jpy
        data_type: double
      - name: gbp
        data_type: double
      - name: chf
        data_type: double
      - name: nzd
        data_type: double
      - name: cad
        data_type: double
      - name: hkd
        data_type: double
      - name: sgd
        data_type: double
      - name: myr
        data_type: double
      - name: twd
        data_type: double
      - name: krw
        data_type: double
      - name: idr
        data_type: double
      - name: cny
        data_type: double
      - name: sdr
        data_type: double
  - name: s1_aud2000
    description: "AUD rate for 2000"
    +columns:
      - name: usd
        data_type: double
      - name: eur
        data_type: double
      - name: jpy
        data_type: double
      - name: gbp
        data_type: double
      - name: chf
        data_type: double
      - name: nzd
        data_type: double
      - name: cad
        data_type: double
      - name: hkd
        data_type: double
      - name: sgd
        data_type: double
      - name: myr
        data_type: double
      - name: twd
        data_type: double
      - name: krw
        data_type: double
      - name: idr
        data_type: double
      - name: cny
        data_type: double
      - name: sdr
        data_type: double
  - name: s1_aud2010
    description: "AUD rate for 2010"
    +columns:
      - name: usd
        data_type: double
      - name: eur
        data_type: double
      - name: jpy
        data_type: double
      - name: gbp
        data_type: double
      - name: chf
        data_type: double
      - name: nzd
        data_type: double
      - name: cad
        data_type: double
      - name: hkd
        data_type: double
      - name: sgd
        data_type: double
      - name: myr
        data_type: double
      - name: twd
        data_type: double
      - name: krw
        data_type: double
      - name: idr
        data_type: double
      - name: cny
        data_type: double
      - name: sdr
        data_type: double
  - name: s1_aud2020
    description: "AUD rate for 2020"
    +columns:
      - name: usd
        data_type: double
      - name: eur
        data_type: double
      - name: jpy
        data_type: double
      - name: gbp
        data_type: double
      - name: chf
        data_type: double
      - name: nzd
        data_type: double
      - name: cad
        data_type: double
      - name: hkd
        data_type: double
      - name: sgd
        data_type: double
      - name: myr
        data_type: double
      - name: twd
        data_type: double
      - name: krw
        data_type: double
      - name: idr
        data_type: double
      - name: cny
        data_type: double
      - name: sdr
        data_type: double