
version: 2

models:
  - name: tickers_nyse
    description: "{{ doc('Tickers') }}"
    columns:
      - name: ticker
        description: "Stock Ticker"
      - name: name
        description: "Stock Name"
  - name: hist_aapl
    description: "Apple Stock"
    columns:
      - name: date
        description: "Date field"
        data_tests:
          - not_null
      - name: price
        description: "Stock Price"

